#%RAML 1.0 Library
types:
  Checkout:
    properties:
      id:
        displayName: id
        required: false
        type: integer
        format: int64
      paymentType:
        displayName: number
        required: true
        type: string
        enum: ["VISA CARD","MASTERCARD","CASH","AMEX CARD"]
      orders_id:
        displayName: ordersId
        required: true
        type: integer