#%RAML 1.0 Library
types:
  Table:
    properties:
      id:
        displayName: id
        required: false
        type: integer
        format: int64
      number:
        displayName: number
        required: true
        type: integer
        format: int64
      orders_id:
        displayName: orders
        required: true
        type: integer